name: Autograding Tests
'on': ["push"]


jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
   
    - name: install clingo
      run: |
        conda install -c potassco clingo
    - name: clingo results details
      run:  |
       python asp/test.py -e asp/seeknumbers.lp -i asp/instances -s asp/solutions -t 180
      
    - name: testgrader
      id: testgrader
      uses: education/autograding-io-grader@v1
      with:
        test-name: testgrader
        setup-command: ''
        command: python asp/test.py -e asp/seeknumbers.lp -i asp/instances -s asp/solutions -t 180|grep success |wc -l
        input: ''
        expected-output: '16'
        comparison-method: exact
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TESTGRADER_RESULTS: "${{steps.testgrader.outputs.result}}"
      with:
        runners: testgrader
